### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by pushred** [imgix/imgix.js#10]
Any reason this hasn't been published to npm yet? It works fine in my node project fetching from GitHub, but I'm missing out on npm's versioning features and performance.

**Comment by jacktasia** [comment]
Hi Eric,

Thanks for the message and reminder! I just added it now. [https://www.npmjs.com/package/imgix.js](https://www.npmjs.com/package/imgix.js)

I hope that helps. Please let me know if there's  anything else I can do.

**Comment by pushred** [comment]
Crazy fast, thanks!
