### ISSUE TITLE
SEO implications

### ISSUE THREAD

**Issue by tompazourek** [imgix/imgix.js#103]
If I have an imgix-powered image like:

```
<img
  ix-src="https://assets.imgix.net/unsplash/hotairballoon.jpg?w=300&amp;h=500&amp;fit=crop&amp;crop=right"
  alt="A hot air balloon on a sunny day"
>
```

The search engine crawler will not pick up the image, since it needs an `src` attribute. But if I put an `src` attribute, the browser will do an **extra request** for it.

Is there a way of solving this issue to **allow the images to be crawlable**?

I'm thinking about:
```
<noscript>
<img src="image-for-search-engines" />
</noscript>
```

But I'm not really sure it'll get picked up by a crawler. When I for example switch off JS in Chrome, it just renders the img tag as text, not as an image.

Any ideas on this? Alternative solutions? I think it's an important concern and should be addressed in a documentation.

Thanks for your time.

**Comment by paulstraw** [comment]
Hey @tompazourek, thanks for the message. This is a potential issue with any front-end source-replacement tool (including lazysizes and previous versions of imgix.js). Thankfully, Google and Bing (which powers Yahoo! search) both execute JavaScript these days, so it shouldn't cause any major issues.

Here's a SO post that links to some Google and Bing posts on the topic: http://stackoverflow.com/questions/1785083/how-do-web-crawlers-handle-javascript/1785101#1785101

Google also provides a super handy "Fetch as Google" tool that you can use to verify that they're seeing your site how you want: https://support.google.com/webmasters/answer/6066468?hl=en

I'm going to close this issue, but feel free to reopen if you have other questions or concerns!

-paul

**Comment by tompazourek** [comment]
Hi @paulstraw, thanks for the insights and useful links.

For imgix, it will probably not be an issue then, but I wonder about how this is handled with lazy loading scripts, since they often load stuff only after they enter viewport. These would then work only if Google's crawler would actually scroll through the page or trigger the right events, which I assume it doesn't. Although I might be wrong.

I'll have to do some experiments with the tools you mention.
