### ISSUE TITLE
[2.2.3] images not showing on some iOS webviews when using crossorigin=anonymous and imgix.fluid()

### ISSUE THREAD

**Issue by sebcante** [imgix/imgix.js#105]
Hi guys,

I came into a scenario where using imgix.js (2.2.3) inside iOS 9 and inside a UIWebview, the fluid images where not showing.
After troubleshooting it, it turned out that those browsers (iOS UIWebview) will not execute `img.onload()` when using `crossorigin=anonymous`. In those cases `img.onerror()` are called for some reasons (this does not happen on Mobile Safari)

I am unsure if you are still maintaining 2.x.x but i could propose some very tiny changes that would make it work. 

Let me know if you would be happy to take those changes in.

A) https://github.com/iPowow/imgix.js/commit/1c272954b48ee5f7168563bcc7a366b843350a40 (listen to onerror too so that we can trigger the callback)
B) https://github.com/iPowow/imgix.js/commit/17477ed6f866ac7b9ef53fa2efe5a1a72e008229 ( force onload to trigger when using non <img> tag)

thanks

-seb

**Comment by paulstraw** [comment]
Hey @sebcante, sounds good to me. I'd be happy to merge a PR for this into the `master-2.x` branch.

**Comment by paulstraw** [comment]
Alrighty, merged in #106 and released as 2.2.4! Thanks for the PR, @sebcante.
