### ISSUE TITLE
Limit the number of breakpoints?

### ISSUE THREAD

**Issue by sebelga** [imgix/imgix.js#113]
Hi,

I was wondering if there was a way of limiting the number of breakpoints for the srcset. I have now 35, from 100w to 1920w, and I am wondering if that is not too much.. It seems a lot and it means less chance to hit the cache, no?

**Comment by jayeb** [comment]
Hey Sebelga,

You're correct that the more breakpoints you provide, the more chances you have at missing the cache. The key, though is striking the right balance: serving an oversized image to a client, especially a mobile client, will negatively affect download time, bandwidth, and battery life (as the device's GPU is typically used for rendering the resized image). Depending on how complicated your image request is (affecting how long it takes our imaging servers to render), a cache miss for a mobile user could be almost entirely offset by these factors.

We think the breakpoints provided by this library do a good job of splitting the difference, but I'd be open to the idea of adding some overrides if you think this isn't the case. Do you have any suggestions for how this interface might look?

**Comment by sebelga** [comment]
Hi jayeb,
Thanks for the information. I don't have much experience with responsive images/srcset/picture so I will take your expertise on it. I am discovering imgix and I really like it so far. If I see the need later and I have some interface in mind to override the breakpoints I will let you know.

I amwondering then about the DOM impact of having 35 srcset for each image on a page with infinite scroll for an image gallery (more than 100 on the page for ex.) Does that have some impact (for the low end devices) for the rendering of the page?

thanks

**Comment by jayeb** [comment]
Naw, nothing to worry about. The `srcset` attribute is going to have the same effect on a page's rendering as a normal `src` attribute, regardless of how many URLs are provided inside of it.

I'm gonna close this issue for now, but I'm happy to answer any other questions you have. If you decide that overriding imgix.js's breakpoints is important to you and you have some ideas on how we might implement it, feel free to re-open.
