### ISSUE TITLE
Override config settings on a per-image basis

### ISSUE THREAD

**Issue by dbchristopher** [imgix/imgix.js#119]
Hi,
I'm running into a weird race condition when trying to use imgix.js with lazysizes, with above-the-fold images. It seems that lazysizes is attempting to images before imgix.js has a chance to generate the `data-srcset` list. 

I'd love to have the ability to override global config settings and generate standard srcset markup on individual images when I know they'll be above the fold.

Thanks!

**Comment by dbchristopher** [comment]
As an alternative, which might actually work better, is an ability to add a class after imgix has processed each image. The solution aFarkas recommended for lazysizes is to "Only render the class lazyload to images after/as soon as you created the data-srcset attribute." But I don't believe there are currently any hooks to tie into for each image as it gets processed

**Comment by jayeb** [comment]
Hey @dbchristopher, sorry for the late reply on this. I think the most flexible solution here would be to add an optional callback to `imgix.init()`, but the way imgix.js is designed, it doesn't really make much sense for us to do so.

The library is designed to auto-initialize once the DOM is ready (see [imgix.js#L44-L61](https://github.com/imgix/imgix.js/blob/master/src/imgix.js#L44-L61)), which means you won't really have an option to pass in a callback unless you make use of the [autoInit=false `<meta>` tag](https://github.com/imgix/imgix.js#disabling-auto-initialization) to turn off this feature. Then, theoretically, you could initialize the library yourself and pass in a callback easily, like this:
```js
imgix.init(null, function() { /* callback */});
```

This is kind of silly, though, for one important reason: when `imgix.init()` runs, it's completely synchronous. There's no event-handling and no `window.setTimeout()` in its execution, so a callback is kind of useless. If you want to ensure that a piece of code runs after `imgix.init()` is done its work, just execute it afterwards.

For starters, you'll need to include this `<meta>` tag in your `<head>`, to disable auto-init:
```html
<meta property="ix:autoInit" content="false">
<!-- And the necessary config options for lazysizes, of course -->
<meta property="ix:srcAttribute" content="data-src">
<meta property="ix:srcsetAttribute" content="data-srcset">
<meta property="ix:sizesAttribute" content="data-sizes">
```

And then do something like this (using jQuery's here for brevity's sake):
```js
$(document).ready(function () {
  imgix.init();

  // All images should have the "data-srcset" attribute at this point
  $('img[data-srcset]').addClass('lazyload');
});
```

Hope this helps!
