### ISSUE TITLE
disabling imgix setters

### ISSUE THREAD

**Issue by 719media** [imgix/imgix.js#121]
I'm using lazysizes with imgix.js

Lazysizes has an option where you can use data-sizes="auto" which is quite nice. However, imgix.js overwrites this field. Now, I can use something like
`<meta property="ix:sizesAttribute" content="data-ignoreMe">`
to have imgix write the field to some nonsensical attribute, but it seems like it would be helpful to have a way to just ignore having this happen at all (to prevent needless data fluff).

One way would be to just wrap the code in imgix.js with like
`if(this.settings.sizesAttribute !== false) {}`
and then you could do
`<meta property="ix:sizesAttribute" content="false">`
another could be to allow the <meta> tags to set NULLs, (remove the `if (metaTagValue !== null) {` line in imgix.js) and then do the same check as described above:
`if(this.settings.sizesAttribute !== null) {}`

thoughts?

**Comment by jayeb** [comment]
Yea, seems reasonable.

**Comment by jayeb** [comment]
Closed by #123.
