### ISSUE TITLE
imgix cannot properly trigger lazysizes due to processing order on <img>

### ISSUE THREAD

**Issue by idolab** [imgix/imgix.js#125]
Situation (the followings are set)
imgix.config.srcAttribute = 'data-src';
imgix.config.srcsetAttribute = 'data-srcset';
imgix.config.sizesAttribute = 'data-sizes';

1.  `<img class="lazyload" ix-src="..." >` is processed by lazysizes.js. At that imgix.js has not yet processed the <img>, no `data-srcset` is rendered on the <img>. lazysizes updates nothing and  change the class from `lazyload` to `lazyloaded`
2. imgix.js init with `ix-initialized="ix-initialized"` and set `data-src`,  `data-srcset`
3. lazysizes.js failed to recognize the change

Solution: Add a settings that allow imgix.js add a class after it initialized an `<img>`
something like `ix-class="lazyload"`.

p.s. lazysizes's attrchange plugin does not 100% work on this issue.

**Comment by jayeb** [comment]
@idolab These two scripts should execute in the order they're included on the page. If you simply change the order so imgix.js runs before lazysizes, your problem should be solved.

**Comment by idolab** [comment]
@jayeb do imgix.js observe new DOM element / use MutationObserver or it only run once?

**Comment by jayeb** [comment]
imgix.js only runs once automatically. It's idempotent, so it can be safely re-run as often as you need (say, when you add a new element to the page) and elements that had already been processed will be skipped the second time. You can read about this in the README: https://github.com/imgix/imgix.js/blob/master/README.md#imgix-init-idempotency
