### ISSUE TITLE
Console errors caused by fractional DPRs as a result of browser zoom

### ISSUE THREAD

**Issue by dtbdunnm** [imgix/imgix.js#126]
If the user zooms their browser out, e.g. to 90%, this can cause the browser to have a fractional DPR. This results in the variable `maxScreenWidthRequired` in the function targetWidths() being a fractional number.

A `srcset` entry is generated using this width, which causes follow-on errors that are dumped to the JS console.

Suggest the following change is made to the `targetWidths()` function:

Original:
```
maxScreenWidthRequired = hasWin ?
        maxPossibleWidth * dpr :
        MAXIMUM_SCREEN_WIDTH;
```

Suggested change:

```
maxScreenWidthRequired = Math.floor(hasWin ?
        maxPossibleWidth * dpr :
        MAXIMUM_SCREEN_WIDTH);
```

Issue reproduces on Mac OS X Chrome 61.0.3163.100 (Official Build) (64-bit).

**Comment by jayeb** [comment]
Sounds good to me. @dtbdunnm if you want to put together a pull request for this change that would be awesome. If not, I'll try to get this in next week.
