### ISSUE TITLE
Add default params configuration

### ISSUE THREAD

**Issue by jeremyfrank** [imgix/imgix.js#129]
**Feature Request:**

It would be awesome to be able to automatically pass a set of default parameters with each imgix request. For example, I'd like to have `auto=format,compress` and `fit=crop` sent with every request and not have to specify them within every `ix-params` object.

Perhaps something like `imgix.config.defaultParams = object` could work well for this?

**Comment by jayeb** [comment]
I think this is a really cool idea, and we will definitely implement it.

@jeremyfrank If you wanna take a swing at a PR, please do! Otherwise we'll put it on our roadmap and take care of it at some point in the near future.
