### ISSUE TITLE
Information on how width is set

### ISSUE THREAD

**Issue by adamkuipers** [imgix/imgix.js#13]
For some of our images, imgix is requesting an image with a height but not a width, which is resulting in very large images, in some cases larger than the original. 

I haven't yet been able to reduce what I'm working with into a contained example but could you point me to either documentation or the source code of interest where the query strings are being calculated?

Thanks.

**Comment by jacktasia** [comment]
Hi Adam,

I assume you're talking about `imgix.fluid`? If you want to set a height AND width ensure you're using `fit=crop` and you have both `fitImgTagToContainerWidth` and `fitImgTagToContainerHeight` set to true. Here's [all the config options](https://github.com/imgix/imgix.js/blob/master/docs/api.md#imgix.fluid) for `imgix.fluid` and [the relevant source](https://github.com/imgix/imgix.js/blob/master/dist/imgix.js#L2270) for setting height and width on the query string.

I hope that helps. If you are able to make a contained example of a possible bug/edge-case with imgix.js please let us know. Thanks!

**Comment by adamkuipers** [comment]
The fit to crop did the trick, thanks!
