### ISSUE TITLE
Make reloading browser-cached images possible

### ISSUE THREAD

**Issue by T0TProduction** [imgix/imgix.js#136]
I have a problem where after changing profile pictures (saving as the same file though), I purge it from imgix.net, but the browser has still cached the old version.
According to [this post](https://stackoverflow.com/questions/1922910/force-browser-to-clear-cache) adding a query to the source URL, e.g. with a timestamp, would fix that, but I see no easy way to add it with this library. 
Adding a 'recache' (bool) option which adds this to the URL and could then be "reloaded" via 'imgix.init()' (or a dedicated 'imgix.recache()' which only checks for img's with the 'recache' parameter? )again after I change a variable which I assigned 'recache' to would be a nice option.

I'm using Nuxt.js with a self-made Vue port of imgix.js, which essentially just uses 'imgix.init()' after loading the page.

**Comment by sherwinski** [comment]
Hi @T0TProduction, thanks for the ticket and I think your instincts are correct here. Unfortunately, it's not likely we'll get around to adding this feature to the library anytime soon. 
My best suggestion for right now would be to add a cache-busting parameter to the `ix-params` attribute. This can either be done when the page is being constructed, or by [turning off imgix.js's auto-init](https://github.com/imgix/imgix.js#disabling-auto-initialization) and populating the `ix-params` attributes on your images dynamically via JS.

**Comment by T0TProduction** [comment]
That's the workaround I was looking for, adding it via ix-params works just fine, thanks.
I assumed that ix-params only allows params that imgix.net would accept.
