### ISSUE TITLE
Error in IE 10 and below due to `const`

### ISSUE THREAD

**Issue by tedw** [imgix/imgix.js#137]
Hi there,

I just started using Imgix and am a big fan so far. The only issue I’ve run into is that the script fails on IE 10 and below because of this one `const` ([browser support](https://caniuse.com/#feat=const)):
https://github.com/imgix/imgix.js/blob/dfce2e9c9cbf10feb95974c3404215f329448084/src/imgix.js#L57

https://github.com/imgix/imgix.js/blob/dfce2e9c9cbf10feb95974c3404215f329448084/dist/imgix.js#L267

Would you all mind changing that `const` to a `var`, or maybe providing a transpiled version of the script? I know hardly anyone uses IE 10 these days but this seemed like a pretty minor change and would allow those few holdouts to get images.

Thanks!

**Comment by sherwinski** [comment]
Hi @tedw, glad to hear that! No problem at all, I'll go ahead and swap those out for you 👍

**Comment by tedw** [comment]
Awesome, thanks!
