### ISSUE TITLE
Dynamically changing the data-src attribute

### ISSUE THREAD

**Issue by coniel** [imgix/imgix.js#14]
I'm using Meteor JS which is dynamically changing the value of the ```data-src``` attribute of my image container. My problem is that imgix isn't picking up the changes. Even if I re-run ```imgix.fluid();``` after changing the ```data-src```, the ```src``` attribute isn't updated.

It works fine if I directly set the ```src``` attribute, but I would like to use ```imgix.fluid();```.

**Comment by jacktasia** [comment]
Thanks for reporting this. We didn't really have this use-case in mind when we originally made imgix.js. If you can provide a small self-contained MeteorJS example of the (not currently working) functionality you want then I'd be happy to update imgix.js ASAP to get this working for you.

**Comment by jacktasia** [comment]
Hi @coniel,

 If you can't provide an example of your use-case with MeteorJS then another thing to try (that should work) would be saving your reference to `imgix.fluid` and then explicitly telling `imgix.fluid` you updated the `data-src`.

For example:
```
var myFluid = imgix.fluid(),
	myImg = document.getElementById('myimg');

myImg.setAttribute('data-src', 'http://jackangers.imgix.net/chester.png');
myFluid.updateSrc(myImg);

```
and here's a [working codepen](http://codepen.io/anon/pen/YPmJMM) example. I hope this helps.

**Comment by jacktasia** [comment]
I am closing this issue since the `updateSrc` example above should work for your needs and I haven't heard back. Please re-open if it doesn't. Thanks!

**Comment by ralfschimmel** [comment]
@jacktasia this is not working as described, also the codepen is not working. I'm trying to do this in Ember and cannot seem to get it working. Any hints, or an updated codepen perhaps?

**Comment by ralfschimmel** [comment]
After a deepdive in the code of 2.0.0 I found this solution;

```
var elem = $('#yourFluidDomElement');
elem.url = new imgix.URL(younewimagesrc);
yourFluid.updateSrc(elem);
```

**Comment by kellysutton** [comment]
Hi @ralfschimmel,

Glad to hear you were able to find something to work for you. If you're using Ember, you should check out our Ember addon: https://github.com/imgix/ember-cli-imgix

**Comment by KristerV** [comment]
hi. unfortunately updateSrc does not fix it anymore. Even your codepen is [broken](http://codepen.io/anon/pen/YPmJMM). Also ralfschimmel's solution does not work.

this is pretty hard, can't find any way of updating data-src.

**Comment by jayeb** [comment]
@KristerV You're right, the method to accomplish this has changed a bit since last April. Here's a more modern Codepen that shows an example of updating an image's source on the fly: http://codepen.io/jayeb/pen/ZbRXpO

Hope it helps! As we prefer to keep GitHub issues limited to bug reports and feature requests, I'd like to request that you write into support@imgix.com if you run into more trouble getting this working. I promise  I'll grab your ticket as soon as I see it come in :smile:
