### ISSUE TITLE
Ability to preview and crop _before_ upload

### ISSUE THREAD

**Issue by patrickberkeley** [imgix/imgix.js#18]
Does imgix.js offer the ability preview and crop/resize/etc. an image _before_ it's uploaded? If so, can you point me to an example?

**Comment by jacktasia** [comment]
Hi Patrick,

Thanks for the message. We're actually currently working on a crop plugin for imgix.js. Our official stance is originals should be uploaded to your origin and all transformations should happen via imgix. That said, the crop plugin's API will have a `getImageData()` method where you can get the image data for just the cropped area and you can use that to upload to your origin if you want. imgix has no data store for uploading. We only fetch images from your origin.

**Comment by patrickberkeley** [comment]
Okay, thanks for the info.
