### ISSUE TITLE
Versioning problem?

### ISSUE THREAD

**Issue by rarkins** [imgix/imgix.js#19]
Were the last two releases tagged incorrectly?

`bower` lists these releases:
```
  - 1.0.18
  - 1.0.17
  - 1.0.16
  - 1.0.15
  - 1.0.14
  - 1.0.13
  - 1.0.12
  - 1.0.11
  - 1.0.10
  - 1.0.9
  - 1.0.8
  - 1.0.7
  - 1.0.6
  - 1.0.5
  - 1.0.4
  - 1.0.3
  - 1.0.2
  - 1.0.1
  - 1.0.0
  - 0.1.20
  - 0.1.19
```
Note the last two.

`bower.json` lists `1.0.20` as the current release.

@jacktasia is it possible that the last two releases were tagged as `0.1.19` and `0.1.20` instead of `1.0.19` and `1.0.20`?

![image](https://cloud.githubusercontent.com/assets/6311784/7349885/8a798952-ecfc-11e4-9fc2-c19d6da19391.png)

**Comment by jacktasia** [comment]
Yup, good catch. I've tagged the most recent version `1.0.20` correctly now. 19 was out for less than a day. Please let me know if doesn't resolve the issue for you. Thanks for reporting this.
