### ISSUE TITLE
React is not defined

### ISSUE THREAD

**Issue by raducretu** [imgix/imgix.js#213]
Trying to use the `<ix-picture>` tag and I get this error.

I am trying to use this in Nuxt.js, with the plugins installed correctly. It works fine when I try to use the `<ix-img>` tag alone.

Any ideas?

Thanks

**Comment by ericdeansanchez** [comment]
Hey 👋 @raducretu thanks for opening this issue!

>Trying to use the <ix-picture> tag and I get this error.

When you say "**this error**", what specific error are you referring to?

**Comment by raducretu** [comment]
Hi @ericdeansanchez ,

Thanks for looking into this. 
The error is: React is not defined
It is abhit strage since I use Vue

Thanks

**Comment by ericdeansanchez** [comment]
Ah, of course, now I can see that the error is in the title. Yes, this is strange. Let me look into this, I think I know what the issue might be.
