### ISSUE TITLE
display:none bug

### ISSUE THREAD

**Issue by gitmiggi** [imgix/imgix.js#27]
When the container of an image is set to <code>display:none</code> and the page is resized, it causes a (potentially large) request of the image set to the width of the window. 

Steps to recreate:
1. Enable imgix.js on an <code>&lt;img&gt;</code> tag
2. Set <code>display:none</code> to container after image has been loaded in.
3. Resize page and inspect element to see the large width imgix request.

Test here by uncommenting the <code>display:none</code> in <code>.default</code> class.
http://codepen.io/miggi/pen/CGnKm

**Comment by jayeb** [comment]
Fixed! See PR: #28.
