### ISSUE TITLE
Lazy Load Response Lag

### ISSUE THREAD

**Issue by gitmiggi** [imgix/imgix.js#30]
There appears to be a bit of lag in response to the lazy load behavior. Even setting the offset for activation as the entire height of the container, there is a degree of lag in response to the loading of those images.

*Update:* debounce should be set to 1, or some other faster value by default. It's causing the lag with the default implementation, making it feel unresponsive.  

http://codepen.io/miggi/pen/QwejGq

**Comment by jayeb** [comment]
The default debounce value is already set to 200. Are you recommending we lower it, or do you think there's a bug in the implementation?

**Comment by jayeb** [comment]
Per an IRL discussion, the issue here is probably that we should be throttling scroll events, rather than debouncing.
