### ISSUE TITLE
maxWidth / maxHeight in fluid bug

### ISSUE THREAD

**Issue by gitmiggi** [imgix/imgix.js#32]
In this pen: 
http://codepen.io/miggi/pen/MwbLEK/

I am setting maxWidth and maxHeight, however the values are being ignored, and I'm guessing it is in favor of fitImgTagToContainerHeight. I would expect the max values to be the end all be all.

**Comment by brinsknaps** [comment]
I'm experiencing the same... any progress on this?

**Comment by jayeb** [comment]
@brinsknaps At the moment, no. The code that handles this is fairly convoluted and misses a number of corner cases like this. It desperately needs to be rewritten, but at the moment I simply don't have the time for it.

If you can give me an isolated case of what you're trying to accomplish, I'd be happy to help you find a workaround! Send me a JSFiddle or something and we'll work through it.

**Comment by brinsknaps** [comment]
@jayeb Hi Jason, thanks for the prompt response! I've moved on since my comment, but if I come across a similar issue I'll definitely send an example over.

**Comment by jayeb** [comment]
Closing this issue, since it's no longer relevant since the release of imgix.js 3.0.0.
