### ISSUE TITLE
`fitImgTagToContainerWidth` ignores fit modes

### ISSUE THREAD

**Issue by jayeb** [imgix/imgix.js#33]
Seems like no matter what you set, the `fitImgTagToContainerWidth` and `fitImgTagToContainerHeight` parameters of `imgix.fluid()` will override the `fit` param of the current URL.

**Comment by jayeb** [comment]
Yup, this is the problem code: https://github.com/imgix/imgix.js/blob/master/src/core.js#L2171-L2173

I want to poke around a bunch before making a change to make sure that I don't accidentally ruin whatever case this conditional is there to handle.

**Comment by zeman** [comment]
Any progress on this? I'd like my images to responsively scale within a container but use fit=clip so their proportions are maintained. Is there any alternative way to do this?

**Comment by jayeb** [comment]
@zeman `fit=clip` is the default fit setting so as long as you aren't specifying both `fitImgTagToContainerWidth` AND `fitImgTagToContainerHeight` (sounds like you want only the former), you should have no problems.

If you're having trouble with this, would you write in to support@imgix.com and we can figure out a solution off-thread? We prefer to use GitHub issues specifically for bug reports.

**Comment by jayeb** [comment]
(This should not have been closed, my apologies)

**Comment by jayeb** [comment]
Closing this issue, since it's no longer relevant since the release of imgix.js 3.0.0.
