### ISSUE TITLE
Color Palette JSON byte size

### ISSUE THREAD

**Issue by gitmiggi** [imgix/imgix.js#39]
Please reduce the class size of the unique generated ids for the color palette values to save on file size.

http://migimages.imgix.net/illustration/sketchbooked-012.jpg?auto=format&class=tmp_aHR0cDovL21pZ2ltYWdlcy5pbWdpeC5uZXQvaWxsdXN0cmF0aW9uL3NrZXRjaGJvb2tlZC0wMTIuanBnP2F1dG89Zm9ybWF0JmNyb3A9dG9wJmZpdD1jcm9wJml4anN2PTEuMS4w&colors=16&crop=top&fit=crop&ixjsv=1.1.0&palette=css

**Comment by jayeb** [comment]
Oh sweet lord. Willfix.

**Comment by jayeb** [comment]
Fixed by #40
