### ISSUE TITLE
Allow lazy-loading on scroll events for containers with overflow

### ISSUE THREAD

**Issue by kellysutton** [imgix/imgix.js#43]
Right now, we only listen to scroll events on the `window` for triggering lazy-loads.

We should instead figure out a good way of also listening to scroll events on containers that may obscure images-to-be-lazy-loaded.

**Comment by jayeb** [comment]
Yup, our scroll-handler story needs a lot of work right now. This issue will definitely be addressed by whatever we end up doing.

**Comment by rocketnova** [comment]
:+1: I'm using imgix on a project that involves overflow. This would be really helpful.

**Comment by joshfrench** [comment]
We just ran into this. A superficial fix would be to add an optional `lazyLoadContainer` setting to allow the user to specify an element (or array of elements?) to add the scroll listener to, which would default to `window`.

I'm happy to submit a patch, but I suspect I'm over-simplifying it so I thought I'd toss it out for discussion before I got started. Thoughts?

**Comment by jayeb** [comment]
I think that approach sounds pretty good to me.

**Comment by joshfrench** [comment]
I have a patch in the works, but I'm having trouble getting the specs to pass even on master. Is there anything special I need to do to mirror your dev environment?

Specifically, after a clean checkout & npm install this test fails for me on Chrome & Firefox and halts the rest of the test suite:
```
.fluid Firing onLoad callbacks fires an onLoad callback initially FAILED
        Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

**Comment by paulstraw** [comment]
Hey @joshfrench, I'm unable to replicate these failing tests on a clean checkout. Can you send through your Node version and the full log you're seeing, just in case?

**Comment by joshfrench** [comment]
@paulstraw I'm on Node 5.4.0 / NPM 3.8.3.

I had to jump through some hoops just to get karma running in the first place, my process & the resulting test failure are documented here: https://gist.github.com/joshfrench/2fd6572e20fd978e78cb

Before you dive into that though, let me know what node & npm you're using in house and I'll just try it on those versions first.

**Comment by paulstraw** [comment]
Oddly, when I use Node 5.4.0 with npm 3.8.3 I also get the peer dep issue for requirejs and phantomjs, but the tests run fine. Can you give it a try with Node 4.4.1 / npm 2.14.20?

**Comment by joshfrench** [comment]
Same error -- I tracked this down to a timeout in `.fluid Firing onLoad callbacks fires the onLoad callback again when the image's src is updated`.

Strangely, if I run the tests with _either_ Chrome or Firefox they pass; I only get the error when Karma runs more than one browser. Maybe something around [here](https://github.com/imgix/imgix.js/blob/master/tests/fluid_test.js#L71-L72) is leaking across tests and throwing off the count? Not sure why it's only affecting me, though ¯\\\_(ツ)_/¯

I'll proceed with the PR and just run the tests separately locally.

**Comment by joshfrench** [comment]
See #89

**Comment by paulstraw** [comment]
Thanks a lot @joshfrench! That's merged, and I'm closing this issue. :grin:
