### ISSUE TITLE
buildUrl strips out port

### ISSUE THREAD

**Issue by scashin133** [imgix/imgix.js#44]
If a url has a port, the port is not included when getUrl is called.

```js
imageUrl = new imgix.URL('http://localhost:5000/asdf')
imageUrl.getUrl() /* Returns http://localhost/asdf */
```
I would expect the port to be unchanged.

This will trigger with default images that are not served up through imgix but are being lazy loaded with imgix.js.

**Comment by jayeb** [comment]
Thanks for the report! I'll get a fix out sometime in the next couple of days. If you want to tackle it yourself, feel free to submit a PR :)
