### ISSUE TITLE
Are polyfills really just for IE 8?

### ISSUE THREAD

**Issue by wuservices** [imgix/imgix.js#46]
The docs mention that polyfills are for IE8, but I see a Promise polyfill. Due to that at least, am I correct in assuming I need polyfills enabled for my build if I want to support IE at all vs just for IE8?

Also, is onready needed at all if you place imgix.js or at least the initialization code, at the end of the body past all images?

**Comment by jayeb** [comment]
Yes, you're correct on both accounts.

You'll need the Promise polyfill to support IE8, but it doesn't have to be the one provided in imgix.js. Any ol' Promise polyfill will do. I know, it's a bit of an eye-roller--we're aiming to factor this requirement out in the near future.

You're also correct about the `onready` method--you can skip it entirely if your imgix.js initializing happens at the end of the body.

We try to keep GitHub issues clear for bug reports and feature-requests as much as possible, but if you've got further questions I'm happy to answer them. Just write into support@imgix.com and I'll make sure the ticket comes into my inbox!

**Comment by wuservices** [comment]
To clarify, I think the docs should reflect that you need the polyfills to support any version of IE including 9, 10, 11 since they don't support promises. It currently reads like the polyfills are only to support IE8. However, not a big deal if it's being reworked anyways.

Thanks for the other clarifications and I'll contact support if I have any other questions.
