### ISSUE TITLE
allow cleaning up of FluidSet

### ISSUE THREAD

**Issue by kayoub5** [imgix/imgix.js#48]
right now there is no way to destroy the `FluidSet` object created by `imgix.fluid()` this causing memory leaks once the image is removed from the DOM tree.

**Comment by jayeb** [comment]
Yea, this is a major oversight in the way imgix.js is constructed at the moment. We plan to address this in the next major release.

**Comment by jayeb** [comment]
Note for context: the problem is not with the `FluidSet` object itself, but rather with the event-listeners created in association with a new `FluidSet` object.

**Comment by rarkins** [comment]
+1

When is the next major release planned?

**Comment by jayeb** [comment]
We don't have a solid roadmap for this at the moment, sorry. I wish I had a more satisfying answer for you, but the fact is that we're strapped for time at the moment. If you'd like to take a stab at a patch and submit a PR, I'm happy to review and get this moving.

**Comment by jayeb** [comment]
Closing this issue, since it's no longer relevant since the release of imgix.js 3.0.0.
