### ISSUE TITLE
Changing an image URL

### ISSUE THREAD

**Issue by pushred** [imgix/imgix.js#49]
Question: the [`URL.autoUpdateImg`][1] method refers to a change in the image URL, but it's not clear how I can update the URL of an instance.

In my case I have a single image element for which I'm dynamically setting the `src`. I'm trying to automatically generate and apply a imgix URL with my desired params whenever I change the source. If I simply update the attribute, the URL is overwritten. I also tried redefining the `urlParts.baseUrl` property on the instance — same outcome.

My code looks like this:

```js
if (self.imgixPreview) {
  self.$previewElement.attr('src', imgixPath(previewImage.src));
} else {
  self.imgixPreview = new imgix.URL(imgixPath(previewImage.src), {
    q: 90
  });
  self.imgixPreview.attachImageTo('.photos__preview');
  self.imgixPreview.autoUpdateImg('.photos__preview');
}

```

[1]: https://github.com/imgix/imgix.js/blob/master/docs/api.md#imgix.URL+autoUpdateImg

**Comment by pushred** [comment]
I'm also not having any luck with the method provided in https://github.com/imgix/imgix.js/issues/14. I'm setting `data-src` and calling `updateSrc` on the same element, but nothing happens. Also tried calling a reload method I saw in the prototype:

```js
if (self.imgixPreview) {
  self.$previewElement[0].setAttribute('data-src', imgixPath(previewImage.src));
  self.imgixPreview.updateSrc(self.$previewElement[0]);
  self.imgixPreview.reload();
} else {
  self.imgixPreview = imgix.fluid({
    fluidClass: 'photos__preview',
    ignoreDPR: true,
    onChangeParamOverride: function () {
      return {
        q: 90
      }
    }
  });
}
```

**Comment by jayeb** [comment]
@pushred I think what you're looking for here is the `imgix.URL.setUrl()` method, which appears to be sadly undocumented.

We like to keep GitHub issues just for addressing bugs in the library, so I'm gonna close this ticket. If I'm misunderstanding your issue, would you write in to support@imgix.com so we can discuss off-thread?

**Comment by KristerV** [comment]
well i guess this is a bug then if it's not documented. I also need this and contacting support takes too much time.
