### ISSUE TITLE
Significant amount of processing time spent in urlParser

### ISSUE THREAD

**Issue by scashin133** [imgix/imgix.js#50]
Trying to get to the bottom of some scroll jank I noticed that imgix.js library spends a lot of time processing during scroll even after all images have been loaded.

![imgix.js processing time](http://content.screencast.com/users/scashin133/folders/Jing/media/89eebb35-38ea-4561-92c2-00806d95b450/00000117.png)

We have since increased our throttle timeout from the default 200ms to 2000ms, which has decreased the amount of time spent in urlParser.

**Comment by jayeb** [comment]
Hey Sean, thanks for opening this issue. Realistically, the scroll-handler shouldn't be calling `parseUrl` at *all*, but this part of the code is a little soupy and methinks it could use a fresh approach.

I'm gonna carve out a few days next week dedicated specifically to re-architecting and slimming down the scroll handling in imgix.js. I'll keep you posted on the progress.

**Comment by jayeb** [comment]
Some improvements have been made in #52! I'm curious to know how much these speed up performance on your page.

**Comment by scashin133** [comment]
I commented in the PR but figured I'd post here as well and call this closed.

I am seeing a significant improvement after this change. If you look at the image below the left is with v1.1.0 and right is v1.1.3. Went from taking 23% to 6%. When I change the throttle to 2 seconds it naturally gets even better (see the second image). Great work.

![old vs new performance](http://content.screencast.com/users/scashin133/folders/Jing/media/efcf73aa-0de1-4370-acc7-3d2016f5a90c/00000121.png)
![with 2 second throttle](http://content.screencast.com/users/scashin133/folders/Jing/media/9a0eec0f-814d-42db-bee6-948a354f7c6d/00000122.png)
