### ISSUE TITLE
Properly handle `crossorigin` attribute on images

### ISSUE THREAD

**Issue by jayeb** [imgix/imgix.js#51]
Right now, because we proxy image-loading in the `imgix.setElementImageAfterLoad` method, we're not respecting the `crossorigin` attribute on images. This can result in duplicate requests when the "cached" image is applied to the `<img/>` element.

**Comment by Seismik** [comment]
Thanks for raising this be good to see the outcome.

**Comment by jayeb** [comment]
This is fixed by #59.
