### ISSUE TITLE
Loading maximum possible width for invisible containers

### ISSUE THREAD

**Issue by bbuchalter** [imgix/imgix.js#6]
I've got a responsive site, and have a case where a particular section is hidden for mobile and shown for desktop. Using imgix.js for the hidden section requests the maximum possible size for those images. :(

**Comment by dylanvalade** [comment]
@jacktasia yes, `ignoreHiddenElements` is a good option.  In my related case, some content specifically for displayed only on mobile or tablet+.  Also as you scroll down the desktop page you get a smaller version of the logo but that smaller logo element is hidden on load.

**Comment by jayeb** [comment]
Hey Dylan, I just rolled out a fix for hidden elements last week. I think if you grab v1.0.25, your problem should be solved: https://github.com/imgix/imgix.js/releases/tag/1.0.25

Will you try it out and let me know?

**Comment by danchristian** [comment]
@jayeb What was the fix for this?

**Comment by jayeb** [comment]
@danchristian This issue was addressed in:
- 50b019a73216043b53323ff3e192994c128eeb4b
- b7a0f61eaded38f5daaa428af7bde4681a905e75
- 0f196d007160b9e939afc1dda436a73c85ea8af6

If you're running imgix.js version 1.0.25 or above, you should be good to go. Are you still seeing an issue with this?

**Comment by danchristian** [comment]
No issue. I just couldn't find an explanation of what happens anywhere (Imgix docs etc). But I guess this line explains it...

> it('doesn\'t download images when the imgix.fluid image is hidden'

**Comment by daveyjones** [comment]
I too had to look through the code to see how hidden divs would be handled. It might be a good idea to add some documentation around this.
