### ISSUE TITLE
trimcol vs. trimcolor

### ISSUE THREAD

**Issue by pushred** [imgix/imgix.js#61]
So the docs are telling me [`trimcol`][1] but imgix.js wants it to be [`trimcolor`][2].

Who wins?

[1]: https://www.imgix.com/docs/reference/trim#param-trimcol
[2]: https://github.com/imgix/imgix.js/blob/master/src/core.js#L924

**Comment by jayeb** [comment]
It's `trimcol`! Thanks for the catch, willfix.

**Comment by pushred** [comment]
:clap: thanks =)

**Comment by jayeb** [comment]
Apologies @pushred, but the correct parameter is `trimcolor`. Our docs are confused! I'm backing this change out, and will make sure the docs get fixed.
