### ISSUE TITLE
Remove Promise dependency by switching imgix.URL#getColors to use palette=json

### ISSUE THREAD

**Issue by kellysutton** [imgix/imgix.js#65]
There's only one point in the code base that requires the use of Promises, and that's how we compute the colors of a file. We use Promises to do some hacky discovery of these colors

Because [palette=json](https://www.imgix.com/docs/reference/palette#param-palette) is now available in the API, we should be able to greatly simplify and harden `imgix.URL#getColors` along with removing the Promise dependency.

**Comment by jayeb** [comment]
Closed by #68
