### ISSUE TITLE
fit=fill on bg image doesnt result in height value of container specified. 

### ISSUE THREAD

**Issue by gitmiggi** [imgix/imgix.js#71]
Works correctly when fitmode is set to crop, both a height and width will be set. Does not work with fit=fill or clamp. 

Testing on this image. 

url(https://assets.imgix.net/sandbox/sandboxlogo.ai?bg=fafafa&colorquant=100&fit=fill&fm=png8&ixjsv=1.2.0&page=1&w=326)

Should be setting a height of 300 from the container. Works when passing along fit=crop

**Comment by gitmiggi** [comment]
How it currently Behaves:
![image](https://cloud.githubusercontent.com/assets/1854764/10556255/58c19594-7433-11e5-88b9-1d5f0e6d0fd9.png)

How it behaves with  v1.1.2 ( and should behave ) 
![image](https://cloud.githubusercontent.com/assets/1854764/10556253/43e6c342-7433-11e5-98e9-2bc1fb9968fc.png)

`var bgFillFluidOptions = {
      fluidClass: 'imgix-fluid-fill-bg',
      updateOnResizeDown: true,
      updateOnPinchZoom: true,
      pixelStep: 1,
      autoInsertCSSBestPractices: true,
      lazyLoad: true,
      lazyLoadColor: 9,
      lazyLoadOffsetVertical: 4000,
       onChangeParamOverride: function(w, h, e) {
        return {
            fit: 'fill'
        };
      }
    }`

**Comment by jayeb** [comment]
@gitmiggi Any chance you've got a codepen somewhere demonstrating this?

**Comment by ojdupuis** [comment]
I have the same issue here with fit = fill :

**Comment by jayeb** [comment]
Closing this issue, since it's no longer relevant since the release of imgix.js 3.0.0.
