### ISSUE TITLE
Imgix.js with Angular?

### ISSUE THREAD

**Issue by mcblum** [imgix/imgix.js#78]
I'm running into the problem where Imgix isn't converting the data-src url to src. I think it's because I'm using angular. Any idea how to integrate? I see you have a React library but not one for Angular :)

**Comment by mcblum** [comment]
Resolved! Wrapping the call in a $timeout request fixed it. Thanks for a great service.

**Comment by jayeb** [comment]
Glad you were able to come up with a solution. I think at some point in the future we'll release an official Angular directive that integrates directly with imgix.js, but for now it sounds like your solution did the trick.
