### ISSUE TITLE
Extracting BG image when there are parentheses in the image URL

### ISSUE THREAD

**Issue by lukechesser** [imgix/imgix.js#79]
We have an old user generated image that has a `(3)` in the filename. Why? No idea haha (we've since taken to renaming images so this doesn't happen, but we're still left with older images that potentially have weird characters in them).

If we're using that image as a background image, the parentheses break the CSS attribute, because it escapes the style early:

```
<div style="background-image: url(https://images.unsplash.com/some-photo(3)-something-else);"></div>
```

So to fix it, we could wrap the background-image style attribute in parentheses but that seems to break the imgix.js `getRawBackgroundImage` regex.

You can see the specific image here: https://unsplash.com/photos/4uCSqP5OKiI (it's broken)

Any way we could update the regex to account for parentheses?

Thanks.

**Comment by jayeb** [comment]
Ah, thanks for the catch. I'll put together a fix for this in the coming
week.

**Comment by jayeb** [comment]
@lukechesser Version 2.1.0 is out with this fix: https://github.com/imgix/imgix.js/releases/tag/2.1.0
