### ISSUE TITLE
Using fit=facearea results in fit=crop for imgix.fluid

### ISSUE THREAD

**Issue by gitmiggi** [imgix/imgix.js#83]
Using an image with imgix-fluid applied ignores fit=facearea and sets it back to fit=crop.

**Comment by ojdupuis** [comment]
Any fit different from fit=crop, results in a url generated by the JS with fit=crop

**Comment by jayeb** [comment]
Closing this issue, since it's no longer relevant since the release of imgix.js 3.0.0.
