### ISSUE TITLE
Minor: Old version number in imgix.js

### ISSUE THREAD

**Issue by vancura** [imgix/imgix.js#90]
Hi,

A minor issue, but still an issue. The version number of 2.2.0 imgix.js returned to server is still 2.1.0. See https://github.com/imgix/imgix.js/blob/16a23696e9577733c0957b85c4ffda5758fbb63a/dist/imgix.js#L272

Thanks,
Vaclav

**Comment by paulstraw** [comment]
Ah, thanks for the issue report @vancura. I'll get this fixed up shortly.

**Comment by paulstraw** [comment]
This should be all set now in 2.2.1. Thanks again, @vancura!
