### ISSUE TITLE
dpr is set despite ignoreDPR set to "true"

### ISSUE THREAD

**Issue by pedroaguilar** [imgix/imgix.js#91]
Expected Behavior:

Setting `ignoreDPR` to "true" should prohibit the `dpr` parameter from being set.

Currently, this does not appear to be the case. Relevant ticket: https://imgix1.zendesk.com/agent/tickets/5774

**Comment by jayeb** [comment]
Closing this issue, since it's no longer relevant since the release of imgix.js 3.0.0.
